### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by edgarnadal** [thunderpush/thunderpush-js#4]
Hello,

I can't install thunderpush-js through bower, there's not any tag.

Can you help with that?

**Comment by jrschumacher** [comment]
That's a good question. I can't remember if I every registered it. Looking into this

**Comment by jrschumacher** [comment]
I just created tag `v0.9.2` Please let me know if that helped.

**Comment by jrschumacher** [comment]
@edgarnadal

**Comment by edgarnadal** [comment]
Excelente.

Why are you using lodash and underscore?? There are practically the same, you don't need both.

**Comment by edgarnadal** [comment]
@jrschumacher

**Comment by jrschumacher** [comment]
@edgarnadal I prefer lodash for its performance but either is fine. I am using common methods. 

I saw this trick in another package. I was under the impression it said lodash is required but underscore is optional `*`. However if you know a better way of doing this that would be good too.

**Comment by jrschumacher** [comment]
All this said, I am going to be releasing version 2 in a few months which will have additional supports and may not need lodash (not yet decided though).

**Comment by edgarnadal** [comment]
I can help :)

**Comment by jrschumacher** [comment]
Thanks!

**Comment by jrschumacher** [comment]
@edgarnadal you may also be interested in this project which is really stagnant https://github.com/jrschumacher/angular-thunderpush

**Comment by edgarnadal** [comment]
Excellent

Im doing that!

Let me check it.
